version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-vulnerable
      - api-secure

  api-vulnerable:
    build: ./api-vulnerable
    environment:
      - MODE=vulnerable

  api-secure:
    build: ./api-secure
    environment:
      - MODE=secure