name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
      name: Remote Deployment with Docker-Compose
      with:
        ssh_host: ${{ secrets.HETZ_VPS_IP }}
        ssh_private_key: ${{ secrets.HETZ_VPS_SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.HETZ_VPS_SSH_USER }}
        ssh_pass: ${{ secrets.HETZ_VPS_SSH_PASS }}
        docker_compose_prefix: api-sec-lab
        pull: true # Update images when pulling


